### ISSUE TITLE
Help text doesn't include CLI arguments & flags

### ISSUE THREAD

**Issue by imrehg** [agherzan/git-mirror-me#7]
When running the script, without reading the README, it's not obvious what flags are available, since the help doesn't include them.

```shell
$ ./git-mirror-me -help
git-mirror-me is a CLI tool that facilitates mirroring git repository.

CLI arguments/flags

Environment variables
[...snip...]
```

**Comment by agherzan** [comment]
It was also fixed in https://github.com/agherzan/git-mirror-me/pull/2. Thanks for checking it out.
